language: python

python:
    - "3.4"
    - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install nose mock coverage pep8
    - python setup.py develop

# command to run tests, e.g. python setup.py test
script:
    - pep8 --ignore=E501 jenkinsapi/*.py
    - pylint --rcfile=pylintrc jenkinsapi/*.py --disable R0912
    - nosetests jenkinsapi_tests
